In [7]:
import os
from pyhive import hive
import pandas as pd
import re
import pickle as pl
data_conn = hive.Connection(host='10.254.5.100',
                           port=10000,
                           username='ETL',
                           database='default')
# df = pd.read_sql('../sql/train_2020.sql',data_conn)
df = pd.read_sql(open('../sql/train_2020.sql','r').read(),data_conn)

In [8]:
df.head()

line_id station_id        日期 星期     疫情  季节       总量  \
0      92       9229  20200415  3  2.793   4    168.0   
1      05       0523  20200415  3  2.793   4  24476.0   
2      06       0625  20200415  3  2.793   4   6384.0   
3      13       1325  20200415  3  2.793   4   8636.0   
4      97       9712  20200415  3  2.793   4   4043.0   

                                                分时序列  
0    [3,11,30,11,7,5,5,2,4,1,10,15,20,22,13,5,3,0,1]  
1  [288,1523,5764,7781,4356,898,649,641,490,365,2...  
2  [15,109,410,567,279,133,132,164,139,151,167,44...  
3  [23,56,196,349,231,126,82,110,133,99,159,475,1...  
4  [56,344,940,1236,588,154,118,91,111,71,52,52,7...

In [12]:
pl.dump(df,open('train_data_2020','wb'))

In [20]:
df[(df['station_id'] =='0117') & (df['日期']=='20200605')]

line_id station_id        日期 星期     疫情  季节      总量  \
10863      01       0117  20200605  5  1.461   4  7228.0   

                                                    分时序列  
10863  [89,72,173,149,170,299,378,477,423,485,558,871...

In [21]:
df[(df['station_id'] =='0117') & (df['日期']=='20200910')]

line_id station_id        日期 星期   疫情  季节       总量  \
34817      01       0117  20200910  4  0.0   4  13159.0   

                                                    分时序列  
34817  [17,334,268,270,411,651,880,1097,1063,878,1179...

In [23]:
len(df)

36147

In [24]:
df_train = df[(df['日期'] <='20200515')]
df_eval = df[df['日期'] >'20200515']

In [27]:
import numpy as np
arr_train = np.mean(np.array(eval(df_train['分时序列'].values)),axis = 0)
arr_eval = np.mean(np.array(eval(df_eval['分时序列'].values)),axis = 0)

ValueError: source code string cannot contain null bytes

In [42]:
# df_train['分时序列'].values
[eval(i) for i in df_train['分时序列'].values]

TypeError: 'numpy.ndarray' object is not callable

In [48]:
df_eval['分时序列'].values
arr_eval = np.array([eval(i) for i in df_eval['分时序列'].values])

TypeError: 'numpy.ndarray' object is not callable

In [38]:
arr_eval.shape

(30839, 19)

In [49]:
eval(df['分时序列'].values[0])

TypeError: 'numpy.ndarray' object is not callable

In [56]:
[eval(i) for i in df.loc[0,'分时序列']]

TypeError: 'numpy.ndarray' object is not callable

In [55]:
df_eval['分时序列'].values

array(['[36,148,374,367,152,77,99,118,142,142,233,298,463,323,155,94,53,16,2]',
       '[66,514,1188,916,382,172,140,149,133,145,149,171,226,234,153,91,65,27,5]',
       '[95,718,1772,1210,266,130,124,148,66,81,68,120,164,192,111,61,39,16,2]',
       ...,
       '[44,333,1150,1023,402,236,213,217,262,243,173,253,722,803,360,286,215,72,2]',
       '[58,349,814,1058,833,681,784,699,764,693,801,1115,1640,1802,1071,736,567,336,56]',
       '[102,379,529,265,99,62,66,51,50,57,56,80,117,72,28,22,18,3,0]'],
      dtype=object)

In [4]:
import numpy as np
df_train = df[(df['日期'] <='20200515')]
df_eval = df[df['日期'] >'20200515']


arr_eval = np.array([eval(i) for i in df_eval['分时序列'].values])
arr_train = np.array([eval(i) for i in df_train['分时序列'].values])

res = np.mean(arr_eval,axis=0)/np.mean(arr_train,axis=0)

In [1]:
import pickle as pl
df = pl.load(open('train_data_2020','rb'))

In [5]:
res

array([1.68449195, 1.60802757, 1.43302717, 1.29312534, 1.24198478,
       1.40494979, 1.47033397, 1.44083404, 1.45803457, 1.45670728,
       1.45789909, 1.40159216, 1.44051273, 1.36402689, 1.28897186,
       1.39838877, 1.5200523 , 1.59568418, 1.58639628])

In [7]:
pl.dump(res,open('increse_index','wb'))

In [8]:
list(res)

[1.684491949349088,
 1.6080275679329796,
 1.4330271712699114,
 1.2931253427247893,
 1.2419847775265045,
 1.4049497892432226,
 1.4703339731372622,
 1.4408340437816065,
 1.458034568699127,
 1.4567072825462712,
 1.4578990896373984,
 1.401592163029476,
 1.4405127329750218,
 1.364026889998179,
 1.2889718576648381,
 1.3983887748621038,
 1.5200523027387098,
 1.595684181090308,
 1.5863962762892057]

In [9]:
a = [1.684491949349088,
 1.6080275679329796,
 1.4330271712699114,
 1.2931253427247893,
 1.2419847775265045,
 1.4049497892432226,
 1.4703339731372622,
 1.4408340437816065,
 1.458034568699127,
 1.4567072825462712,
 1.4578990896373984,
 1.401592163029476,
 1.4405127329750218,
 1.364026889998179,
 1.2889718576648381,
 1.3983887748621038,
 1.5200523027387098,
 1.595684181090308,
 1.5863962762892057]

In [10]:
a

[1.684491949349088,
 1.6080275679329796,
 1.4330271712699114,
 1.2931253427247893,
 1.2419847775265045,
 1.4049497892432226,
 1.4703339731372622,
 1.4408340437816065,
 1.458034568699127,
 1.4567072825462712,
 1.4578990896373984,
 1.401592163029476,
 1.4405127329750218,
 1.364026889998179,
 1.2889718576648381,
 1.3983887748621038,
 1.5200523027387098,
 1.595684181090308,
 1.5863962762892057]

In [34]:
t1 = np.array([eval(i) for i in df[(df['station_id'] == '0825') & (df['日期']=='20200910')]['分时序列'].values])
t1

array([[  36,  184,  652,  577,  280,  198,  216,  307,  328,  333,  413,
         564, 1254, 1583, 1337, 1092, 1137,  290,   11]])

In [28]:
t2 = np.mean(np.array([eval(i) for i in df[(df['station_id'] == '0825') & (df['日期'].isin(['20200908', '20200907', '20200909']))]['分时序列'].values]),axis=0).astype(int)
t2

array([  17,  246,  621,  547,  367,  798, 1361, 1645, 1692, 2066, 2849,
       4121, 3418, 2133, 1666, 1199, 1126,  282,   14])

In [35]:
np.divide(t2,t1)

array([[0.47222222, 1.33695652, 0.95245399, 0.94800693, 1.31071429,
        4.03030303, 6.30092593, 5.35830619, 5.15853659, 6.2042042 ,
        6.89830508, 7.30673759, 2.72567783, 1.34744157, 1.2460733 ,
        1.09798535, 0.99032542, 0.97241379, 1.27272727]])

In [43]:
#coding=utf-8
import numpy as np
import pandas as pd



def get_index(df,infer_start_date):
    df_train = df[(df['日期'] < infer_start_date)]
    df_eval = df[df['日期'] >= infer_start_date]

    arr_eval = np.array([eval(i) for i in df_eval['分时序列'].values])
    arr_train = np.array([eval(i) for i in df_train['分时序列'].values])

    res = np.mean(arr_eval, axis=0) / np.mean(arr_train, axis=0)
    res[0],res[18] = 1,1 #开始时段跟结束时段不做缩放
    return res



In [44]:
get_index(df,'20200815')

array([1.        , 1.4170904 , 1.28783376, 1.2134595 , 1.2381831 ,
       1.42250589, 1.48850294, 1.47593245, 1.50187471, 1.51367797,
       1.51510618, 1.43595299, 1.35163147, 1.2759081 , 1.23193746,
       1.26909862, 1.34090447, 1.39382122, 1.        ])

In [47]:
np.divide(t2,t1)/get_index(df,'20200815')

array([[0.47222222, 0.94345182, 0.73957836, 0.78124316, 1.05857872,
        2.83324171, 4.23306245, 3.6304549 , 3.43473163, 4.09876098,
        4.55301759, 5.08842395, 2.01658357, 1.05606475, 1.01147448,
        0.86516945, 0.73855031, 0.69766035, 1.27272727]])

In [ ]:
np.di